export const data = [
  {
    itemno: 1,
    name: "Spring Rolls",
    price: 148,
    cuisines: ["Fast Food"],
  },
  {
    itemno: 2,
    name: "Honey Chilli Patato",
    price: 140,
    cuisines: ["Fast Food", "Street Food"],
  },
  {
    itemno: 3,
    name: "BhelPuri",
    price: 150,
    cuisines: ["Fast Food", "Street Food"],
  },
  {
    itemno: 4,
    name: "Sambhar Vada",
    price: 100,
    cuisines: ["South Indian"],
  },
  {
    itemno: 5,
    name: "Margherita Pizza",
    price: 199,
    cuisines: ["Pizza"],
  },
  {
    itemno: 6,
    name: "Chole Bhature",
    price: 100,
    cuisines: ["North Indian"],
  },
  {
    itemno: 7,
    name: "Masala Dosa",
    price: 120,
    cuisines: ["South Indian"],
  },
  {
    itemno: 8,
    name: "Dum aloo",
    price: 230,
    cuisines: ["North Indian"],
  },
  {
    itemno: 9,
    name: "Veg Manchurian",
    price: 248,
    cuisines: ["Fast Food", "Street Food"],
  },
  {
    itemno: 10,
    name: "Aloo Tikki",
    price: 80,
    cuisines: ["Street Food", "Fast Food"],
  },
  {
    itemno: 11,
    name: "Samosa",
    price: 100,
    cuisines: ["Street Food" , "Fast Food"],
  },
  {
    itemno: 12,
    name: "Dimsums",
    price: 130,
    cuisines: ["Chinese"],
  },
  {
    itemno: 13,
    name: "Double Cheese Pizza",
    price: 230,
    cuisines: ["Pizza"],
  },
  {
    itemno: 14,
    name: "Paneer Lababdar",
    price: 298,
    cuisines: ["North Indian"],
  },
  {
    itemno: 15,
    name: "Veg Hakka Noodles",
    price: 198,
    cuisines: ["Chinese" , "Street Food"],
  },
  {
    itemno: 16,
    name: "Grilled Chicked lettuce",
    price: 248,
    cuisines: ["Street Food"],
  },
  {
    itemno: 17,
    name: "Cheese and Corn Pizza",
    price: 140,
    cuisines: ["Pizza"],
  },
  {
    itemno: 18,
    name: "Paneer Momos",
    price: 198,
    cuisines: ["Fast Food"],
  },
  {
    itemno: 19,
    name: "Dal Fry",
    price: 250,
    cuisines: ["North Indian"],
  },
  {
    itemno: 20,
    name: "Farm Fresh Pizza",
    price: 230,
    cuisines: ["Pizza"],
  },
];
